Vagrant.configure("2") do |config|

  # -------- web01 --------
  config.vm.define "web01" do |web01|
    web01.vm.box = "generic/ubuntu2204"
    web01.vm.hostname = "web01"

    web01.vm.network "private_network", ip: "192.168.56.11"

    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
  end

  # -------- web02 --------
  config.vm.define "web02" do |web02|
    web02.vm.box = "generic/ubuntu2204"
    web02.vm.hostname = "web02"

    web02.vm.network "private_network", ip: "192.168.56.12"

    web02.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
  end

  # -------- db1 --------
  config.vm.define "db1" do |db1|
    db1.vm.box = "eurolinux-vagrant/centos-stream-9"
    db1.vm.hostname = "db1"

    db1.vm.network "private_network", ip: "192.168.56.13"

    # Provisioning for db1 (install MariaDB)
    db1.vm.provision "shell", inline: <<-SHELL
      sudo yum update -y
      sudo yum install -y wget unzip mariadb-server -y
      sudo systemctl start mariadb
      sudo systemctl enable mariadb
    SHELL

    db1.vm.provider "libvirt" do |libvirt|
      libvirt.memory = "1024"
      libvirt.cpus = 1
    end
  end

end