Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 600
    config.vm.box = "generic/ubuntu2204"
    config.vm.network "private_network", ip: "192.168.56.17"
    config.vm.synced_folder "./scripts", "/opt/scripts"
    
    config.vm.provider "libvirt" do |libvirt|
        libvirt.memory = 1024
        libvirt.cpus = 2
    end
end