Vagrant.configure("2") do |config|
    config.vm.box = "eurolinux-vagrant/centos-stream-9"
    config.vm.network "private_network", ip: "192.168.56.17"

    # Avoid libvirt NFS guest setup on CentOS Stream 9 by forcing rsync.
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.synced_folder "./scripts", "/opt/scripts", type: "rsync"

    config.vm.provider "libvirt" do |libvirt|
        libvirt.memory = 1024
        libvirt.cpus = 2
    end
end