Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.network "private_network", ip: "191.168.56.78"

  # Provisioning script path: scripts/provision.sh
  config.vm.provision "shell", path: "scripts/provision.sh"
end
